- name: Docker Image Build and Push
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t repush/cicdproject java-hello-world/
    - command: docker login -u repush -p "{{ lookup('env', 'PASS') }}"
    - command: docker push repush/cicdproject
    - command: docker logout

- name: Docker Run
  hosts: docker_host
  gather_facts: false
  
  tasks:
    - command: docker container rm -f java-hello-world
      ignore_errors: yes
    - command: docker container run -d -p 8080:8080 --name java-hello-world repush/cicdproject
