- name : Log into DockerHub
  docker_login:
    username: repush
    password: "{{ lookup('env','PASS') }}"
    
- name : Build image and with build args
  docker_image:
    name: myhello
    build:
      path: /path/to/build/dir
      args:
        log_volum: /var/log/myapp
        listen_port: 8080
    source: build
- name: Tag and Push to docker hub
  docker_image:
    name: myhello
    repository: repush/cicdproject
    push: yes
    source: local
