- name: Docker Image Build and Push
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker build --tag repush/cicdproject:"{{ lookup('env', 'BUILD_NUMBER') }}" java-hello-world/
    - command: docker login -u repush -p "{{ lookup('env', 'PASS') }}"
    - command: docker push repush/cicdproject:"{{ lookup('env', 'BUILD_NUMBER') }}"
    - command: docker logout
