- hosts: ansible_host
  gather_facts: no

  tasks:
    #- command: kubectl apply -f java-hello-world/kube_manifest/
    - name: Create Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Daeminset
          metadata:
            name: wordpress
            namespace: default
          spec:
            selector:
              matchLabels:
                app: wordpress
            template:
              metadata:
                labels:
                  app: wordpress
              spec:
                containers:
                  - name: wordpress
                    image: wordpress
                    env:
                    - name: WORDPRESS_DB_HOST
                      value: wordpress.ciz2oqzzzdnw.ap-northeast-2.rds.amazonaws.com
                    - name: WORDPRESS_DB_NAME
                      value: wordpress
                    - name: WORDPRESS_DB_USER
                      value: admin
                    - name: WORDPRESS_DB_PASSWORD
                      value: dkagh1.dkagh1.
                    ports:
                      - containerPort: 80
                        name: wordpress
    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: wordpress
            namespace: default
            labels:
              app: wordpress
          spec:
            type: NodePort
            selector:
              app: wordpress
            ports:
              - port: 80
                targetPort: 80
                nodePort: 31313
